### ISSUE TITLE
Could this be a webpack core plugin?

### ISSUE THREAD

**Issue by mjackson** [van-nguyen/webpack-cdn-plugin#1] opened 2017-06-02 13:40 UTC
Hi!

First of all, I just wanted to say awesome work on this plugin. It looks great!

I [was wondering](https://twitter.com/mjackson/status/870501086779523072) just last night if we could build something like this for unpkg to help people use the CDN in production. 

Right now this works with the webpack html plugin, but could this be a plugin for webpack itself? Instead of extending `HtmlWebpackIncludeAssetsPlugin`, could we just add to the compiler's `chunks` array? Just wondering.

Again, great work and thank you!

**Comment by van-nguyen** [comment] 2017-06-02 14:39
Hello @mjackson,

Thanks for the awesome feedback, I'm really glad it's being useful.

From reading your comments and tweets I was thinking the same thing, but unfornatunely I don't have enough knowledge to touch the core webpack stuff yet. Thought would be easier to leverage existing plugins to do the heavy lifting instead of "re-inventing" the wheel.

Having said that, there are still challenges by design that prevents us from doing this in a configure-less way. For instance we can detect all the imports that are loaded in node_modules, but we will have to scan for the "main" file from their package.json, and most of the time thats just a thin wrapper file and not the full minified built file we want. At this point that is why providing a path is needed, also a global var so webpack knows how to reference it at bare minimal. Hope this all makes sense, perhaps I haven't explored all options yet, if you or anyone can spare some insights in this that would be great.

**Comment by mastilver** [comment] 2017-06-02 14:53
@mjackson This is something I planned to do in the original plugin, although it was not on my priority list (As I'm using html-webpack-plugin)...

Thought I understand, it's needed by some so I will work on it this week-end (https://github.com/mastilver/modules-cdn-webpack-plugin/issues/6) ;)

**Comment by van-nguyen** [comment] 2017-06-03 02:02
First step to remove the `HtmlWebpackIncludeAssetsPlugin` dependency is done, and published to 1.3.0 https://github.com/van-nguyen/webpack-cdn-plugin/commit/d612058c822211c609cc5c3e14108717029ffdfb

**Comment by mjackson** [comment] 2017-06-03 03:17
I was just thinking that by adding it to the chunks array it could potentially be picked up by any HTML generator, or any other process that reads from the webpack stats object. Not a huge deal, but might be nice.

Also, instead of putting stuff into externals, couldn't we just read from stuff the user already put into externals? Just an idea.

**Comment by mjackson** [comment] 2017-06-03 03:22
Actually, I think the way you're doing it may actually be better. It gives us more control over how we load the library from the CDN.

**Comment by van-nguyen** [comment] 2017-06-03 03:43
> I was just thinking that by adding it to the chunks array it could potentially be picked up by any HTML generator, or any other process that reads from the webpack stats object.
I see, that would be nice indeed! I will look into it.

**Comment by van-nguyen** [comment] 2017-09-26 05:21
I gave it a shot some time ago and seems like `webpack-html-plugin` hardcodes the prefix regardless of the publicPath set, not sure they are going to "fix" that. Will close this until further notice.

**Closed by van-nguyen** 2017-09-26 05:21 UTC
