### ISSUE TITLE
webpack4 htmlWebpackPluginBeforeHtmlGeneration is undefined

### ISSUE THREAD

**Issue by wZi** [van-nguyen/webpack-cdn-plugin#19] opened 2018-03-26 03:16 UTC
```
Happy[js]: Version: 5.0.0-beta.3. Threads: 5 (shared pool)
(node:59770) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Happy[js]: All set; signaling webpack to proceed.
~/node_modules/webpack-cdn-plugin/main.js:48
      compilation.hooks.htmlWebpackPluginBeforeHtmlGeneration.tapAsync('WebpackCdnPlugin', (data, callback) => {
TypeError: Cannot read property 'tapAsync' of undefined
```

any solution is helpfully.
Thanks

**Comment by van-nguyen** [comment] 2018-03-28 09:55
Hey @wZi which version of webpack are you using?

**Comment by wZi** [comment] 2018-04-02 03:14
Thanks for your replay.
The webpack version is V4.1.1

**Comment by van-nguyen** [comment] 2018-06-23 06:22
I still can't reproduce this problem, are you able to share you `package.json`?

**Comment by corcoran** [comment] 2018-10-09 21:33
I ran into this issue while using vue-cli and was able to fix it by explicitly importing HtmlWebpackPlugin and registering it as a plugin.

vue.config.js example:
```
const HtmlWebpackPlugin = require('html-webpack-plugin')
const WebpackCdnPlugin = require('webpack-cdn-plugin')
module.exports = {
  configureWebpack: {
    plugins: [
      new HtmlWebpackPlugin(),
      new WebpackCdnPlugin({
        modules: {
          'vue': [
            {name: 'vue', var: 'Vue', path: 'dist/vue.runtime.min.js'},
          ],
        }
      })
    ]
  },
```

**Comment by van-nguyen** [comment] 2018-10-31 21:29
There is a PR to support v3 on a legacy branch, this should resolve once merged #37

**Closed** 2018-11-04 22:49 UTC

**Comment by gauravkhuranacopart** [comment] 2019-10-25 17:00
Well i have observed if we define new WebpackCdnPlugin below new HtmlPlugin the error can be averted
